version: 0.0
os: linux
files:
 - source: donutshop/public
   destination: /var/www/html/public
 - source: donutshop/src
   destination: /var/www/html/src
  - source: donutshop/jsconfig.json
   destination: /var/www/html/jsconfig.json
  - source: donutshop/package-lock.json
   destination: /var/www/html/package-lock.json
  - source: donutshop/package.json
   destination: /var/www/html/package.json
  - source: donutshop/webpack.config.js
   destination: /var/www/html/webpack.config.js
  - source: donutshop/yarn.lock
   destination: /var/www/html/yarn.lock

hooks:
 BeforeInstall:
  - location: scripts/install_dependencies
    timeout: 300
    runas: root
  - location: scripts/start_server
    timeout: 300
    runas: root
 ApplicationStop:
  - location: scripts/stop_server
    timeout: 300
    runas: root
