#!/bin/bash
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
. ~/.nvm/nvm.sh
nvm install node
cd /home/ec2-user/donutshop
npm i
npm install pm2 -g
pm2 start 5
pm2 start 4

